### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by jian-wu**
@mymac80 @rickpelletier 

Changed package name to avoid composer local change.  I've tested it out with my own fork.  However, all the downstream apps need to get the composer.json updated.

### CODE REVIEW

**Comment by rickpelletier** [comment]
This is to avoid defining the orchard fork repo in all of the downstream project composer.json files?

**Comment by jian-wu** [comment]
My guess is that using "doctrine/doctrine1" goes out to packagist and there's the name conflict.

**Comment by rickpelletier** [comment]
What's the conflict error say?  I don't think we should have to modify the composer.json of a forked public repo if we are referencing it correctly from the downstream projects

**Comment by jian-wu** [comment]
There's no conflict error.  Composer simply complains there's local change to the lib.

Every fork does change the name if you look at a few.  That's the main point of using a fork.  I don't think there's an overload feature in composer that allows us to keep the same name.

**Comment by rickpelletier** [comment]
https://stackoverflow.com/questions/13325158/contributing-to-open-source-bundles-from-vendor-directory/27970559#27970559

According to this and other SO questions, there's at least two ways to reference our fork without changing the fork's composer.json:

1)  Use the verbose repository definition
2)  Something about prepending "dev-" on the branch name

In which situations is it complaining about a local change to the Doctrine lib?

**Comment by jian-wu** [comment]
Using dev-master won't complain.  As soon as a specific version is specified, it starts to complain.

**Comment by rickpelletier** [comment]
How about dev-x.y.z?

**Comment by jian-wu** [comment]
This is what I got using `"doctrine/doctrine1": "dev-1.2.5.3"`

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package doctrine/doctrine1 could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.
```

**Comment by jian-wu** [comment]
@rickpelletier any reason why you are against changing the name?

**Comment by rickpelletier** [comment]
I think we can just go back to referencing dev-master instead of a specific version - as long as the orchard/doctrine1 repo is defined locally, it should be preferred over the packagist doctrine/doctrine1 repo.

**Pull request closed without merging**
